services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always
