services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: postgres_container
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data:
